---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "AWS Classifier Demo API"
host: "h3xxn0xnl8.execute-api.us-east-1.amazonaws.com"
basePath: "/demo"
schemes:
- "https"
paths:
  /classify:
    get:
      summary: "Classify item name"
      description: "Для переданного наименования номенклатуры подбирает все классы\
        \ вплоть до конечного на базе классификатора"
      operationId: "classify"
      produces:
      - "application/json"
      parameters:
      - name: "itemName"
        in: "query"
        description: "Наименование номенклатуры"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/modelResponseForClassifiy"
        "400":
          description: "Bad request - ошибка в переданных данных (например, отсутс\
            твует обязательный параметр)"
        "500":
          description: "Internal server error - ошибка подключения к Redis или вне\
            шнему ресурсу"
        "502":
          description: "Bad gateway - ошибка при попытке соединения с внешним серв\
            исом"
        "504":
          description: "Gateway timeout - тайм-аут при подключении к Redis или вне\
            шнему ресурсу"
      security:
      - api_key: []
  /pickAtt:
    post:
      summary: "Determine attributes based on the item name and final class"
      description: "Для переданного наименования номенклатуры и конечного класса о\
        пределяет значения аттрибутов"
      operationId: "pickAtt"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "modelRequestForPickAtt"
        required: true
        schema:
          $ref: "#/definitions/modelRequestForPickAtt"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/modelResponseForPickAtt"
        "400":
          description: "Bad request - ошибка в переданных данных (например, отсутс\
            твует обязательное поле)"
        "500":
          description: "Internal server error - ошибка подключения к Redis или вне\
            шнему ресурсу"
        "502":
          description: "Bad gateway - ошибка при попытке соединения с внешним серв\
            исом"
        "504":
          description: "Gateway timeout - тайм-аут при подключении к Redis или вне\
            шнему ресурсу"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  modelResponseForPickAtt:
    type: "object"
    properties:
      input_item_name:
        type: "string"
      input_final_class_name:
        type: "string"
      input_final_class_code:
        type: "string"
      result:
        type: "array"
        items:
          type: "object"
          properties:
            attribute_name:
              type: "string"
            attribute_type:
              type: "string"
            attribute_example:
              type: "string"
            attribute_decicion:
              type: "string"
  modelResponseForClassifiy:
    type: "object"
    properties:
      input_item_name:
        type: "string"
      result:
        type: "array"
        items:
          type: "object"
          properties:
            class_name:
              type: "string"
            class_code:
              type: "string"
  modelRequestForPickAtt:
    type: "object"
    required:
    - "final_class_code"
    - "final_class_name"
    - "item_name"
    properties:
      item_name:
        type: "string"
      final_class_name:
        type: "string"
      final_class_code:
        type: "string"
